const ShopActionTypes = {
  GET_SELECTED_ROBOTS: 'GET_SELECTED_ROBOTS',
  SET_INITIAL_VALUES: 'SET_INITIAL_VALUES',
  REDUCE_FROM_INVENTORY: 'REDUCE_FROM_INVENTORY',
  FETCH_ROBOTS_BEGIN: 'FETCH_ROBOTS_BEGIN',
  FETCH_ROBOTS_SUCCESS: 'FETCH_ROBOTS_SUCCESS',
  FETCH_ROBOTS_FAILURE: 'FETCH_ROBOTS_FAILURE',
  INCREASE_IN_INVENTORY:'INCREASE_IN_INVENTORY',
  FILTER_ROBOTS:'FILTER_ROBOTS'
};

export default ShopActionTypes;